# This is a basic workflow that is manually triggered

name: integration_test

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - review_requested
    branches:
      - 'main'

jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      checks: write   # Permission to create a Check Run
      contents: write # Permission to write a repository_dispatch requests
    if: contains(github.event.pull_request.labels.*.name, 'integration')
    steps:
      - name: Dump GitHub
        id: github-context
        env:
          JSON: ${{ toJSON(github) }}
        run: echo $JSON

      - name: View context attributes
        id: view-context-attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)  
   
      - name: Report tests check
        id: report-tests-check
        uses: actions/github-script@v7
        with:
          script: |
            const check = await github.checks.create({
              name: 'run tests',
              head_sha: '${{ github.event.pull_request.head.sha }}',
              status: 'queued',
              conclusion: '${{ steps.github-context.outcome }}',
              output: {
                title: 'Run tests',
                summary: 'Results: ${{ steps.github-context.outcome }}'
              },
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log('PR Head sha: ' + check.data);
            core.setOutput('sha', check.data.id);
