# This is a basic workflow that is manually triggered

name: integration_test

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - review_requested
    branches:
      - 'main'

jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    if: contains(github.event.pull_request.labels.*.name, 'integration')
    steps:
    - name: pull_request_target
      run: echo "${{ github.event.pul_request }}"
